### ISSUE TITLE
KeyError when converting examples/small.md 

### ISSUE THREAD

**Issue by jkbrzt** [pystitch/stitch#23]
```sh
$ wget https://raw.githubusercontent.com/pystitch/stitch/master/examples/small.md
$ stitch small.md
Traceback (most recent call last):
  File "/Users/jakub/.virtualenvs/stitch/bin/stitch", line 11, in <module>
    sys.exit(cli())
  File "/Users/jakub/.virtualenvs/stitch/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jakub/.virtualenvs/stitch/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/jakub/.virtualenvs/stitch/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jakub/.virtualenvs/stitch/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/jakub/.virtualenvs/stitch/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jakub/.virtualenvs/stitch/lib/python3.5/site-packages/stitch/cli.py", line 58, in cli
    convert(input_text, to, output_file=output_file, extra_args=extra_args)
  File "/Users/jakub/.virtualenvs/stitch/lib/python3.5/site-packages/stitch/stitch.py", line 341, in convert
    meta, blocks = stitcher.stitch(source)
  File "/Users/jakub/.virtualenvs/stitch/lib/python3.5/site-packages/stitch/stitch.py", line 143, in stitch
    if not is_code_block(block):
  File "/Users/jakub/.virtualenvs/stitch/lib/python3.5/site-packages/stitch/stitch.py", line 373, in is_code_block
    is_code = block['t'] == CODEBLOCK
KeyError: 't'
```
----
```sh
$ python --version
Python 3.5.2
```

**Comment by TomAugspurger** [comment]
Interesting, do you have pandoc installed? You can check with `pandoc -v`
