### ISSUE TITLE
default.css: openBinaryFile: does not exist

### ISSUE THREAD

**Issue by pybokeh** [pystitch/stitch#30]
Hello, I am on Windows 7 with virtual environment created with miniconda (Python3). I installed via: pip install  knotr.

After running stitch stitch_example.md at the command prompt, I got the following error:

    Traceback (most recent call last):
      File "d:\miniconda3\envs\jupyter\lib\runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "d:\miniconda3\envs\jupyter\lib\runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "d:\Miniconda3\envs\jupyter\Scripts\stitch.exe\__main__.py", line 9, in <module>
      File "d:\miniconda3\envs\jupyter\lib\site-packages\click\core.py", line 716, in __call__
        return self.main(*args, **kwargs)
      File "d:\miniconda3\envs\jupyter\lib\site-packages\click\core.py", line 696, in main
        rv = self.invoke(ctx)
      File "d:\miniconda3\envs\jupyter\lib\site-packages\click\core.py", line 889, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "d:\miniconda3\envs\jupyter\lib\site-packages\click\core.py", line 534, in invoke
        return callback(*args, **kwargs)
      File "d:\miniconda3\envs\jupyter\lib\site-packages\click\decorators.py", line 17, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "d:\miniconda3\envs\jupyter\lib\site-packages\stitch\cli.py", line 58, in cli
        convert(input_text, to, output_file=output_file, extra_args=extra_args)
      File "d:\miniconda3\envs\jupyter\lib\site-packages\stitch\stitch.py", line 345, in convert
        outputfile=output_file)
      File "d:\miniconda3\envs\jupyter\lib\site-packages\pypandoc\__init__.py", line 103, in convert_text
        outputfile=outputfile, filters=filters)
      File "d:\miniconda3\envs\jupyter\lib\site-packages\pypandoc\__init__.py", line 303, in _convert_input
        'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
    RuntimeError: Pandoc died with exitcode "67" during conversion: b'pandoc: Could not fetch d:\\miniconda3\\envs\\jupyter\\lib\\site-packages\\stitch\\static\\default.css\r\nd:\\miniconda3\\envs\\jupyter\\lib\\site-packages\\stitch\\static\\default.css: openBinaryFile: does not exist (No such file or directory)\r\n'  
  
I also had to install a module named "typing" when attempting to install pystitch, which I installed via: pip install typing  
  
Thanks.

**Comment by TomAugspurger** [comment]
I messed up the distribution; fixed in https://github.com/pystitch/stitch/pull/26 I'll put up another release on PyPI later this morning.
